name       : rygel
version    : 0.40.0
release    : 15
source     :
    - https://download.gnome.org/sources/rygel/0.40/rygel-0.40.0.tar.xz : d67ecc834ed060337e8fab8cb55a4f3d0c0cce4457e0cd307903a2539f6e2b77
license    : LGPL-2.0-or-later
component  : network.util
summary    : Rygel uPnP Media Server
description: |
    Rygel is a home media solution that allows you to easily share audio, video and pictures, and control of media player on your home network. In technical terms it is both a UPnP AV MediaServer and MediaRenderer implemented through a plug-in mechanism. Interoperability with other devices in the market is achieved by conformance to very strict requirements of DLNA and on the fly conversion of media to format that client devices are capable of handling.
builddeps  :
    - pkgconfig(gee-0.8)
    - pkgconfig(gssdp-1.2)
    - pkgconfig(gstreamer-pbutils-1.0)
    - pkgconfig(gst-editing-services-1.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(gupnp-1.2)
    - pkgconfig(gupnp-av-1.0)
    - pkgconfig(gupnp-dlna-2.0)
    - pkgconfig(libmediaart-2.0)
    - pkgconfig(sqlite3)
    - gtk-doc
    - libunistring-devel
    - tracker-devel # Change to pkgconfig(tracker-sparql-3.0) after upgrade push
    - valadoc
setup      : |
    %meson_configure -Dplugins=gst-launch,lms,media-export,mpris,playbin,tracker3
build      : |
    %ninja_build
install    : |
    %ninja_install
