name       : rygel
version    : 0.42.0
release    : 19
source     :
    - https://download.gnome.org/sources/rygel/0.42/rygel-0.42.0.tar.xz : 006da78677df28caee287c44c29fcd9edcb1b2162423bc7f2dd2dc856b8e2bbb
license    : LGPL-2.0-or-later
component  : network.util
summary    : Rygel uPnP Media Server
description: |
    Rygel is a home media solution that allows you to easily share audio, video and pictures, and control of media player on your home network. In technical terms it is both a UPnP AV MediaServer and MediaRenderer implemented through a plug-in mechanism. Interoperability with other devices in the market is achieved by conformance to very strict requirements of DLNA and on the fly conversion of media to format that client devices are capable of handling.
builddeps  :
    - pkgconfig(gee-0.8)
    - pkgconfig(gst-editing-services-1.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(gupnp-1.6)
    - pkgconfig(gupnp-av-1.0)
    - pkgconfig(gupnp-dlna-2.0)
    - pkgconfig(libmediaart-2.0)
    - pkgconfig(tracker-sparql-3.0)
    - gtk-doc
    - libunistring-devel
    - valadoc
setup      : |
    %meson_configure -Dplugins=gst-launch,lms,media-export,mpris,playbin,tracker3
build      : |
    %ninja_build
install    : |
    %ninja_install
