name       : rygel
version    : 0.38.3
release    : 14
source     :
    - https://download.gnome.org/sources/rygel/0.38/rygel-0.38.3.tar.xz : 08c21a577f7bdad26446a75ffa32778b26842c3b1188165f0b19818559747d00
license    : LGPL-2.0-or-later
component  : network.util
summary    : Rygel uPnP Media Server
description: |
    Rygel is a home media solution that allows you to easily share audio, video and pictures, and control of media player on your home network. In technical terms it is both a UPnP AV MediaServer and MediaRenderer implemented through a plug-in mechanism. Interoperability with other devices in the market is achieved by conformance to very strict requirements of DLNA and on the fly conversion of media to format that client devices are capable of handling.
builddeps  :
    - pkgconfig(gdk-pixbuf-2.0)
    - pkgconfig(gee-0.8)
    - pkgconfig(gssdp-1.2)
    - pkgconfig(gstreamer-app-1.0)
    - pkgconfig(gstreamer-pbutils-1.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(gupnp-1.2)
    - pkgconfig(gupnp-av-1.0)
    - pkgconfig(gupnp-dlna-2.0)
    - pkgconfig(libmediaart-2.0)
    - pkgconfig(sqlite3)
    - pkgconfig(tracker-sparql-2.0)
    - gtk-doc
    - libunistring-devel
    - valadoc
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
