name       : rygel
version    : 0.31.0
release    : 3
source     :
    - http://ftp.gnome.org/pub/gnome/sources/rygel/0.31/rygel-0.31.0.tar.xz : 4a6766b62a1d9dba681caa6009fe90a3f8033a97ac870cd5984bf75a92546a42
license    : LGPL-2.0
component  : network.util
summary    : Rygel uPnP Media Server
description: |
    Rygel is a home media solution that allows you to easily share audio, video and pictures, and control of media player on your home network. In technical terms it is both a UPnP AV MediaServer and MediaRenderer implemented through a plug-in mechanism. Interoperability with other devices in the market is achieved by conformance to very strict requirements of DLNA and on the fly conversion of media to format that client devices are capable of handling.
builddeps  :
    - pkgconfig(gee-0.8)
    - pkgconfig(gssdp-1.0)
    - pkgconfig(gstreamer-app-1.0)
    - pkgconfig(gstreamer-pbutils-1.0)
    - pkgconfig(gupnp-1.0)
    - pkgconfig(gupnp-av-1.0)
    - pkgconfig(gupnp-dlna-2.0)
    - pkgconfig(libmediaart-2.0)
    - pkgconfig(sqlite3)
    - pkgconfig(tracker-sparql-1.0)
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
